server:
  port: 8080

spring:
  config:
    activate:
      on-profile: local # 환경이름설정
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update # update create-drop create
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: 'jdbc:mysql://localhost:3306/gproject?serverTimezone=Asia/Seoul&characterEncoding=UTF-8'
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: localhost
    port: 6379
    password:

  cache:
    type: redis

jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400

cloud:
  aws:
    credentials:
      accessKey: AKIARGKPZUU4ISOGS5QI
      secretKey: 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
    s3:
      bucket: g-app-resource
      directory: local
      cloudfront-url: 'https://d3b7cshusafhca.cloudfront.net/'
      brand-dir: 'local/brand'
      default-image-url: 'https://d3b7cshusafhca.cloudfront.net/local/default/logo-default.png'
      content-dir: 'local/content'
    region:
      static: ap-northeast-2
    stack:
      auto: false
