insert into scraper_brands
(`is_used`, `module_name`, `name`, `status`, `brand_url`, `store_url`, `created_date`, `modified_date`, `last_simulation_datetime`)
values
(b'1', 'FANTOM', 'FANTOM', '1', 'http://www.fantom.co.kr/main/main.asp', 'https://www.creasmall.com/display/brand/main/form?brandGrpNo=2', now(), now(), now()),
(b'1', 'PEARLYGATES', 'PEARLY GATES', '1', 'http://www.pearlygatesgolf.co.kr/main/main.asp', 'https://www.creasmall.com/display/brand/main/form?brandGrpNo=5', now(), now(), now()),
(b'1', 'MASTERBUNNYEDITION', 'MASTER BUNNY EDITION', '1', 'http://www.masterbunnyedition.co.kr/main/main.asp', 'https://www.creasmall.com/display/brand/main/form?brandGrpNo=4', now(), now(), now()),
(b'1', 'STANDREWS', 'ST ANDREWS', '1', 'http://www.standrews.co.kr/main/main.asp', 'https://www.creasmall.com/display/brand/main/form?brandGrpNo=8', now(), now(), now()),
(b'1', 'PING', 'PING', '1', 'http://www.standrews.co.kr/main/main.asp', 'https://www.creasmall.com/display/brand/main/form?brandGrpNo=1', now(), now(), now()),
(b'1', 'DAKS', 'DAKS', '1', 'https://m.daks.co.kr/m2/product/golf', 'https://m.daks.co.kr/m2/product/golf', now(), now(), now()),
(b'1', 'WIDEANGLE', 'WIDEANGLE', '1', 'https://m.k-village.co.kr/wangle', 'https://m.k-village.co.kr/wangle', now(), now(), now()),
(b'1', 'TITLEIST', 'TITLEIST', '1', 'https://titleistapparel.co.kr/', 'https://titleistapparel.co.kr', now(), now(), now()),
(b'1', 'PXG', 'PXG', '1', 'https://www.pxg.co.kr/main/main.asp', 'https://www.pxg.co.kr/main/main.asp', now(), now(), now()),
(b'1', 'NIKEGOLF', 'NIKE GOLF', '1', 'https://www.nike.com/kr/golf', 'https://www.nike.com/kr/golf', now(), now(), now()),
(b'1', 'ADIDASGOLF', 'ADIDAS GOLF', '1', 'https://www.adidas.co.kr/golf', 'https://www.adidas.co.kr/golf', now(), now(), now()),
(b'1', 'ADIDASGOLF', 'ADIDAS GOLF', '1', 'http://www.castelbajac.com', 'https://m.mall.castelbajac.com/', now(), now(), now()),
(b'1', 'CASTELBAJAC', 'CASTELBAJAC', '1', 'http://www.castelbajac.com', 'https://m.mall.castelbajac.com/', now(), now(), now()),
(b'1', 'UNDERARMOURGOLF', 'UNDERARMOUR GOLF', '1', 'https://www.underarmour.co.kr/ko-kr/womens/sports/golf/', 'https://www.underarmour.co.kr/ko-kr/womens/sports/golf/', now(), now(), now()),
(b'1', 'ZENIPION', 'ZENIPION', '1', 'http://m.zenipion.com/', 'http://m.zenipion.com/', now(), now(), now()),
(b'1', 'SOUTHCAPE', 'SOUTHCAPE', '1', 'https://m.southcape.shop/', 'https://m.southcape.shop/', now(), now(), now()),
(b'1', 'JDX', 'JDX', '1', 'https://www.jdx.co.kr/', 'https://www.jdx.co.kr/', now(), now(), now()),
(b'1', 'DUVETICA', 'DUVETICA', '1', 'https://www.duvetica.co.kr', 'https://www.duvetica.co.kr', now(), now(), now()),
(b'1', 'MALBONGOLF', 'MALBON GOLF', '1', 'https://malbongolfkorea.com/', 'https://malbongolfkorea.com/', now(), now(), now()),
(b'1', 'UTAAGOLF', 'UTAA Golf', '1', 'https://m.utaagolf.com/', 'https://m.utaagolf.com/', now(), now(), now()),
(b'1', 'FAIRLIAR', 'FAIRLIAR', '1', 'https://m.fairliar.com/', 'https://m.fairliar.com/', now(), now(), now()),
(b'1', 'BIRDSOFCONDOR', 'BIRDS OF CONDOR', '1', 'https://birdsofcondor.com/', 'https://birdsofcondor.com/', now(), now(), now()),
(b'1', 'CREVE9', 'CREVE9', '1', 'http://m.creve9.com/#enp_mbris', 'http://m.creve9.com/#enp_mbris', now(), now(), now()),
(b'1', 'HORNGARMENT', 'HORNGARMENT', '1', 'https://m.theamall.com/mw/main/horngarment', 'https://m.theamall.com/mw/main/horngarment', now(), now(), now()),
(b'1', 'MARKLONA', 'MARK&LONA', '1', 'https://m.theamall.com/mw/main/markandlona', 'https://m.theamall.com/mw/main/markandlona', now(), now(), now()),
(b'1', 'VICTORYG', 'VICTORY-G', '1', 'https://victory-g.com/apparel', 'https://victory-g.com/apparel', now(), now(), now()),
(b'1', 'MUNSINGWEAR', 'MUNSINGWEAR', '1', 'https://m.munsingwear.co.kr/', 'https://m.munsingwear.co.kr/', now(), now(), now());