# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: g-app

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    # Build
    - name: Build with Gradle
      uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
      with:
        arguments: build
    # Make deploy directory
    - name: Make Directory for deliver
      run: mkdir -p deploy/g-app
    # Copy jar file
    - name: Copy jar
      run: cp ./application/g-app-application/build/libs/*.jar ./deploy/g-app
    # Make Zip file
    - name: Make zip file
      run: zip -r -qq -j ./g-app-build.zip ./deploy/g-app
    # Deliver
    - name: Deliver to AWS S3
      env: 
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY }}
        AWS_S3_ACCESS_SECRET: ${{ secrets.AWS_S3_ACCESS_SECRET }}
      run: |
          aws s3 cp \
          --region ap-northeast-2 \
          --acl private \ 
	  ./g-app-build.zip s3://g-app/
